<a href="https://colab.research.google.com/github/vipinkvpk/python_practice/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

my_list1 = [1,2,3,4]
my_array1 = np.array(my_list1)

In [3]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]
#Make a list of lists
my_lists = [my_list1,my_list2]
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [8]:
#Make multi-dimensional array
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [9]:
#Lets get the size of the array
my_array2.shape

(2, 4)

In [10]:
#Find out the data tyoe of the array
my_array2.dtype

dtype('int64')

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
# Using a range
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])